version: "3.9"

services:
  nginx:
    container_name: nginxdocker

    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 8989:80
      # - 8333:443 #if need ssl
    volumes:
      - ./code/public:/srv/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app
    depends_on:
      - phpfpm

  phpfpm:
    container_name: phpfpmdocker
    build:
      context: ./php/
      dockerfile: Dockerfile
    volumes:
      - ./code:/srv/www
      - ./php/configs:/usr/local/etc/php/conf.d
    networks:
      - app

  mysql:
    build:
      context: ./.mysql/
      dockerfile: Dockerfile
    container_name: mysqldocker
    image: mysql:latest
    ports:
      - 3344:3306
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app

  frontend:
    container_name: reactdocker

    build:
      context: ./frontend/
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3010:3000
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - phpfpm

networks:
  app:
    driver: bridge
